[variables]
    PYTHON_VERSION = "3.10"

[phases.setup]
    nixPkgs = ["python310", "gcc", "xorg.libX11", "xorg.libxcb", "xorg.libXrender", "xorg.libXext", "fontconfig", "libGL", "glib"]

[start]
    cmd = "python manage.py migrate && gunicorn findme_backend.wsgi:application --log-file -"
