# Generated by Django 5.2.11 on 2026-02-13 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('last_seen_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found')], default='MISSING', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_persons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
