# Generated by Django 3.2.25 on 2026-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, verbose_name='Gender')),
                ('last_seen_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen Date')),
                ('last_seen_location', models.TextField(verbose_name='Last Seen Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Physical Description')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_persons/', verbose_name='Person Image')),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found')], default='MISSING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
