# Generated by Django 3.1.12 on 2026-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260213_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='clothing_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
